# Generated by Django 5.0.4 on 2024-04-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_violation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
