# Generated by Django 5.0.4 on 2024-04-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0002_vehicle_last_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('CAR', 'CAR'), ('MOTOBIKE', 'MOTOBIKE'), ('ELECTRIC_BIKE', 'ELECTRIC_BIKE')], max_length=32),
        ),
    ]
